"""Generate ``scripts/server_compat_modules.txt``: the sorted list of
testerkit modules that testerkit-server imports.

docs/44 §1 ("[RULE] testerkit-server depends on testerkit and stays
compatible") requires a cross-repo pre-commit gate that runs the
server's targeted suite whenever a staged change touches a module the
server imports. That gate (``scripts/check-server-compat.sh``) reads
the committed module list produced here rather than re-deriving it at
commit time, so the gate stays fast and the list stays reviewable in a
diff.

This script does the deriving: it AST-scans testerkit-server's
``testerkit_server/``, ``tests/``, ``scripts/`` and ``bench/`` trees
for every ``import testerkit...`` / ``from testerkit... import ...``
statement (excluding ``testerkit_server`` itself) and writes the
distinct dotted module paths, one per line, sorted.

Usage:
    uv run python scripts/generate_server_compat_list.py
    uv run python scripts/generate_server_compat_list.py --check
    uv run python scripts/generate_server_compat_list.py --server-dir ../testerkit-server

``--check`` exits nonzero (without writing) if the committed file would
change — this is what ``tests/test_server_contract.py`` calls to fail
the suite when the two drift apart. If the sibling testerkit-server
checkout can't be found, the script exits nonzero with a clear message
(no silent no-op) unless ``--allow-missing-server`` is passed, which
callers that must not skip in CI use to (loudly) verify the checkout
actually exists first.
"""

from __future__ import annotations

import argparse
import ast
import os
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
_OUTPUT_PATH = _REPO_ROOT / "scripts" / "server_compat_modules.txt"
_SCAN_DIRS = ("testerkit_server", "tests", "scripts", "bench")


def default_server_dir() -> Path:
    """The sibling testerkit-server checkout, overridable via env var.

    Mirrors the convention ``scripts/check-server-compat.sh`` uses:
    testerkit-server lives next to this checkout on disk. Set
    ``TESTERKIT_SERVER_DIR`` to point elsewhere (e.g. a differently
    named worktree).
    """
    override = os.environ.get("TESTERKIT_SERVER_DIR")
    if override:
        return Path(override).expanduser().resolve()
    return (_REPO_ROOT.parent / "testerkit-server").resolve()


def _iter_python_files(server_dir: Path):
    for sub in _SCAN_DIRS:
        base = server_dir / sub
        if base.exists():
            yield from base.rglob("*.py")


def _is_testerkit_module(name: str | None) -> bool:
    return name is not None and (name == "testerkit" or name.startswith("testerkit."))


def scan_server_repo(server_dir: Path) -> set[str]:
    """Return every distinct ``testerkit.*`` (or bare ``testerkit``)
    module dotted-path imported anywhere under ``server_dir``'s scanned
    trees. Excludes ``testerkit_server`` (the server's own package) and
    relative imports (which can never resolve to testerkit)."""
    modules: set[str] = set()
    for path in _iter_python_files(server_dir):
        try:
            source = path.read_text()
        except (OSError, UnicodeDecodeError):
            continue
        try:
            tree = ast.parse(source, filename=str(path))
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    if _is_testerkit_module(alias.name):
                        modules.add(alias.name)
            elif isinstance(node, ast.ImportFrom):
                if node.level:  # relative import (`from . import x`) — never testerkit
                    continue
                if _is_testerkit_module(node.module):
                    modules.add(node.module)  # type: ignore[arg-type]
    return modules


def render(modules: set[str]) -> str:
    header = (
        "# Generated by scripts/generate_server_compat_list.py — do not hand-edit.\n"
        "# Regenerate with:\n"
        "#     uv run python scripts/generate_server_compat_list.py\n"
        "#\n"
        "# One testerkit module per line, dotted-path, sorted. Every module\n"
        "# below is imported somewhere under testerkit-server's\n"
        "# testerkit_server/, tests/, scripts/ or bench/ trees. A staged\n"
        "# change touching any of these files runs the server's targeted\n"
        "# suite before commit (scripts/check-server-compat.sh). Drift\n"
        "# between this file and the server's actual imports is caught by\n"
        "# tests/test_server_contract.py.\n"
    )
    body = "\n".join(sorted(modules))
    return header + body + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--server-dir",
        type=Path,
        default=None,
        help="testerkit-server checkout (default: sibling dir, or $TESTERKIT_SERVER_DIR).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit nonzero if the committed file would change; don't write.",
    )
    args = parser.parse_args()

    server_dir = (args.server_dir or default_server_dir()).resolve()
    if not server_dir.is_dir():
        print(
            f"ERROR: testerkit-server checkout not found at {server_dir}.\n"
            "Set --server-dir or TESTERKIT_SERVER_DIR to point at a checkout.",
        )
        return 1

    modules = scan_server_repo(server_dir)
    rendered = render(modules)

    if args.check:
        current = _OUTPUT_PATH.read_text() if _OUTPUT_PATH.exists() else ""
        if current != rendered:
            print(
                f"DRIFT: {_OUTPUT_PATH} does not match testerkit-server's actual imports "
                f"(scanned {server_dir}).\n"
                "Regenerate with: uv run python scripts/generate_server_compat_list.py",
            )
            return 1
        print(f"{_OUTPUT_PATH} is up to date ({len(modules)} modules).")
        return 0

    _OUTPUT_PATH.write_text(rendered)
    print(f"Wrote {_OUTPUT_PATH} ({len(modules)} modules, scanned {server_dir}).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
